# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev2+gedaa4a0.d20230405'
__version_tuple__ = version_tuple = (0, 1, 'dev2', 'gedaa4a0.d20230405')
